import React from 'react';
import {
  CalendarIcon,
  ContactsIcon,
  DashboardIcon,
  InvoiceIcon,
  ScrumboardIcon,
  TodoIcon,
} from './Svgs';

// Define the navigation links array
export const navLinks = [
  {
    name: 'Dashboard',
    icon: <DashboardIcon />,
    path: '/dashboard',
  },
  {
    name: 'Invoices',
    icon: <InvoiceIcon />,
    path: '/invoices',
  },
  {
    name: 'Scrumboard',
    icon: <ScrumboardIcon />,
    path: '/scrumboard',
  },
  {
    name: 'Contacts',
    icon: <ContactsIcon />,
    path: '/contacts',
  },
  {
    name: 'Todo',
    icon: <TodoIcon />,
    path: '/todo',
  },
  {
    name: 'Calendar',
    icon: <CalendarIcon />,
    path: '/calendar',
  },
];

export const dropdownData = {
  Invoices: [
    { path: '/invoice-list', label: 'Invoice List' },
    { path: '/invoice-templates', label: 'Invoice Templates' },
    { path: '/create-invoice', label: 'Create Invoice' },
    { path: '/invoice-preview', label: 'Invoice Preview' },
  ],
  Scrumboard: [
    { path: '/all-boards', label: 'All Boards' },
    { path: '/project-kanban', label: 'Project Kanban' },
    { path: '/pipeline-kanban', label: 'Pipeline Kanban' },
  ],
  Contacts: [
    { path: '/context-list', label: 'Contact List' },
    { path: '/context-cards', label: 'Contact Cards' },
    { path: '/edit-context', label: 'Edit Contact' },
  ],
  Todo: [
    { path: '/tasklist', label: 'Tasklist' },
    { path: '/gantt', label: 'Gantt' },
  ],
};
export const invoicesData = [
  {
    id: 11201,
    date: '01 Feb, 2020',
    recipient: 'Alice Johnson',
    email: 'alice@company.com',
    status: 'Unpaid',
    amount: '$1,200.00',
    actions: 'Send',
  },
  {
    id: 11202,
    date: '05 Mar, 2020',
    recipient: 'Bob Smith',
    email: 'bob.smith@domain.com',
    status: 'Paid',
    amount: '$3,450.00',
    actions: 'View',
  },
  {
    id: 11203,
    date: '10 Apr, 2020',
    recipient: 'Carol White',
    email: 'carolw@business.net',
    status: 'Draft',
    amount: '$850.00',
    actions: 'Edit',
  },
  {
    id: 11204,
    date: '15 May, 2020',
    recipient: 'David Brown',
    email: 'david.brown@sample.org',
    status: 'Paid',
    amount: '$5,000.00',
    actions: 'View',
  },
  {
    id: 11205,
    date: '20 Jun, 2020',
    recipient: 'Eve Black',
    email: 'eve.black@provider.com',
    status: 'Unpaid',
    amount: '$2,750.00',
    actions: 'Send',
  },
  {
    id: 11206,
    date: '25 Jul, 2020',
    recipient: 'Frank Green',
    email: 'frankg@enterprise.biz',
    status: 'Unpaid',
    amount: '$1,990.00',
    actions: 'Send',
  },
  {
    id: 11207,
    date: '30 Aug, 2020',
    recipient: 'Grace Kelly',
    email: 'grace.kelly@webmail.co',
    status: 'Paid',
    amount: '$3,125.00',
    actions: 'View',
  },
  {
    id: 11208,
    date: '05 Sep, 2020',
    recipient: 'Henry Ford',
    email: 'henryf@innovation.tech',
    status: 'Draft',
    amount: '$4,500.00',
    actions: 'Edit',
  },
  {
    id: 11209,
    date: '10 Oct, 2020',
    recipient: 'Ivy Blue',
    email: 'ivy.blue@creative.org',
    status: 'Paid',
    amount: '$700.00',
    actions: 'View',
  },
  {
    id: 11210,
    date: '15 Nov, 2020',
    recipient: 'Jack Hill',
    email: 'jack.hill@workplace.com',
    status: 'Unpaid',
    amount: '$1,450.00',
    actions: 'Send',
  },
  {
    id: 11211,
    date: '20 Dec, 2020',
    recipient: 'Karen Adams',
    email: 'karen.adams@finance.gov',
    status: 'Paid',
    amount: '$6,800.00',
    actions: 'View',
  },
  {
    id: 11212,
    date: '25 Jan, 2021',
    recipient: 'Leo Clark',
    email: 'leo.clark@network.biz',
    status: 'Draft',
    amount: '$3,320.00',
    actions: 'Edit',
  },
  {
    id: 11213,
    date: '01 Feb, 2021',
    recipient: 'Mia Lee',
    email: 'mia.lee@media.net',
    status: 'Unpaid',
    amount: '$4,700.00',
    actions: 'Send',
  },
  {
    id: 11214,
    date: '05 Mar, 2021',
    recipient: 'Noah Walker',
    email: 'noah.walker@home.org',
    status: 'Paid',
    amount: '$1,950.00',
    actions: 'View',
  },
  {
    id: 11215,
    date: '10 Apr, 2021',
    recipient: 'Olivia Davis',
    email: 'olivia.davis@startup.io',
    status: 'Draft',
    amount: '$2,600.00',
    actions: 'Edit',
  },
  {
    id: 11216,
    date: '15 May, 2021',
    recipient: 'Paul Taylor',
    email: 'paul.taylor@project.co',
    status: 'Unpaid',
    amount: '$8,000.00',
    actions: 'Send',
  },
  {
    id: 11217,
    date: '20 Jun, 2021',
    recipient: 'Quincy Morris',
    email: 'quincy.morris@platform.biz',
    status: 'Paid',
    amount: '$2,900.00',
    actions: 'View',
  },
  {
    id: 11218,
    date: '25 Jul, 2021',
    recipient: 'Rachel Moore',
    email: 'rachel.moore@work.org',
    status: 'Draft',
    amount: '$1,750.00',
    actions: 'Edit',
  },
  {
    id: 11219,
    date: '30 Aug, 2021',
    recipient: 'Sam Wilson',
    email: 'sam.wilson@team.io',
    status: 'Unpaid',
    amount: '$5,600.00',
    actions: 'Send',
  },
  {
    id: 11220,
    date: '05 Sep, 2021',
    recipient: 'Tina Scott',
    email: 'tina.scott@design.net',
    status: 'Paid',
    amount: '$3,000.00',
    actions: 'View',
  },
  {
    id: 11221,
    date: '10 Oct, 2021',
    recipient: 'Uma Evans',
    email: 'uma.evans@school.edu',
    status: 'Draft',
    amount: '$2,150.00',
    actions: 'Edit',
  },
  {
    id: 11222,
    date: '15 Nov, 2021',
    recipient: 'Victor Allen',
    email: 'victor.allen@travel.com',
    status: 'Unpaid',
    amount: '$7,250.00',
    actions: 'Send',
  },
  {
    id: 11223,
    date: '20 Dec, 2021',
    recipient: 'Wendy Harris',
    email: 'wendy.harris@social.org',
    status: 'Paid',
    amount: '$4,400.00',
    actions: 'View',
  },
  {
    id: 11224,
    date: '25 Jan, 2022',
    recipient: 'Xander Lewis',
    email: 'xander.lewis@market.biz',
    status: 'Unpaid',
    amount: '$5,850.00',
    actions: 'Send',
  },
  {
    id: 11225,
    date: '01 Feb, 2022',
    recipient: 'Yvonne Baker',
    email: 'yvonne.baker@tech.co',
    status: 'Draft',
    amount: '$2,950.00',
    actions: 'Edit',
  },
  {
    id: 11226,
    date: '05 Mar, 2022',
    recipient: 'Zane Carter',
    email: 'zane.carter@service.net',
    status: 'Paid',
    amount: '$6,300.00',
    actions: 'View',
  },
  {
    id: 11227,
    date: '10 Apr, 2022',
    recipient: 'Amy Ward',
    email: 'amy.ward@finance.gov',
    status: 'Unpaid',
    amount: '$3,100.00',
    actions: 'Send',
  },
  {
    id: 11228,
    date: '15 May, 2022',
    recipient: 'Brian Reed',
    email: 'brian.reed@creative.org',
    status: 'Draft',
    amount: '$2,400.00',
    actions: 'Edit',
  },
  {
    id: 11229,
    date: '20 Jun, 2022',
    recipient: 'Cathy Stone',
    email: 'cathy.stone@agency.com',
    status: 'Paid',
    amount: '$5,200.00',
    actions: 'View',
  },
  {
    id: 11230,
    date: '25 Jul, 2022',
    recipient: 'Derek Hall',
    email: 'derek.hall@market.net',
    status: 'Unpaid',
    amount: '$4,800.00',
    actions: 'Send',
  },
  {
    id: 11230,
    date: '25 Jul, 2022',
    recipient: 'Jaydeep ',
    email: 'jaydeep@market.net',
    status: 'Unpaid',
    amount: '$4,800.00',
    actions: 'Send',
  },
  {
    id: 11230,
    date: '25 Jul, 2022',
    recipient: 'harsh ',
    email: 'harsh@market.net',
    status: 'Paid',
    amount: '$4,800.00',
    actions: 'Send',
  },
];
